services:
  mysql-db:
    image: mysql:8.0
    container_name: board_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_tasks
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app-board:
    build: .
    container_name: board_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/board_tasks?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db

volumes:
  mysql_data: